### ISSUE TITLE
Command /locate Mansion failing - v1.0.0

### ISSUE THREAD

**Issue by TotalHamman** [McJty/LostCities#46]
Using Lost Cities 1.0.0 and the /locate Mansion command returns "Unable to locate any Mansion feature".  Config is rarecities and confirmed Mansion Structure setting set true.  Attaching screenshot with relevant seed.

Seed - 5467926135997939143
x - 1608
z - 6920

    # Generate mansions
    B:generateMansions=true

![2017-09-23_17 50 23](https://user-images.githubusercontent.com/543169/30777808-1b56d97e-a089-11e7-89d8-c1a761e09f49.png)

**Comment by McJty** [comment]
You need to use 'LostMansion' instead of 'Mansion'. Also only on 1.12

**Comment by TotalHamman** [comment]
Did you modify the command structure?  The Vanilla command is "/locate Mansion" as documented on the Minecraft Wiki - https://minecraft.gamepedia.com/Commands/locate

**Comment by McJty** [comment]
I did not modify it. But I was not able to add mansions to Lost City worlds. So I had to replicate mensions to my own structure which need to have another name. That's why you need to use LostMansion. Because technically they are not the vanilla mansions (but completely look and behave the same) but my own

**Comment by TotalHamman** [comment]
Gotcha, thanks for the explanation.
